# Generated by Django 4.2 on 2023-04-27 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='empdept',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='joiningdate',
        ),
    ]
