# Generated by Django 4.2 on 2023-04-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employeedetail_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Day', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
