# Generated by Django 4.2 on 2023-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='empdept',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='joiningdate',
            field=models.DateField(null=True),
        ),
    ]
