# Generated by Django 4.2 on 2023-05-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeedetail_contact_employeedetail_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Request_Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('empcode', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Reason', models.CharField(max_length=100)),
            ],
        ),
    ]
