# Generated by Django 4.2 on 2023-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_emp_request_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_request_leave',
            name='End_Date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='emp_request_leave',
            name='Start_Date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
