# Generated by Django 4.2 on 2023-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_emp_request_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_request_leave',
            name='End_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='emp_request_leave',
            name='Start_Date',
            field=models.DateField(null=True),
        ),
    ]
