# Generated by Django 4.2 on 2023-05-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_emp_request_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_request_leave',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
