# Generated by Django 4.2 on 2023-05-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_emp_request_leave_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_request_leave',
            name='leave_status',
        ),
        migrations.AddField(
            model_name='emp_request_leave',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emp_request_leave',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
    ]
